apiVersion: v1
kind: Template
metadata:
  annotations:
    desrciption: "Template for generating BuildConfigs with jenkinsPipelineStrategy."
    tags: ""
parameters:
- name: "GIT_URL"
  displayName: "Git URL"
  description: "URL to git source repository containing Jenkinsfile. (e.g. https://github.com/tnozicka/gopipeline.git)"
  required: true
- name: "GIT_REF"
  displayName: "Git Reference"
  description: "Git reference. (branch, ...)"
  value: "master"
- name: "GITHUB_WEBHOOK_SECRET"
  displayName: "GitHub Webhook secret"
  value: "DevConf.cz"
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: hellouniverse-pipeline
    labels:
      app: hellouniverse-pipeline
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "hellouniverse-dev", "namespace": "", "kind": "DeploymentConfig"}]'
  spec:
    triggers:
    - type: GitHub
      github:
        secret: "${GITHUB_WEBHOOK_SECRET}"
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: deploy/Jenkinsfile
    runPolicy: Serial
    source:
      type: git
      git:
        uri: ${GIT_URL}
        ref: ${GIT_REF}
